# authors:
# David Hernandez Lopez, david.hernandez@uclm.es
import os
import sys

DIALOG_TITLE = "Geometric Design Projects"
CONST_NO_COMBO_SELECT = " ... "
RESUME_CONTENT = "Click to view"

AXIS_POINTS_DISTANCE = 10.0
ROI_WIDTH_DEFAULT_VALUE = 50.
ROI_WIDTH_MINIMUM_VALUE = 10.
ROI_WIDTH_MAXIMUM_VALUE = 200.
GSD_COMPUTATION_DEFAULT_VALUE = 0.05
GSD_COMPUTATION_MINIMUM_VALUE = 0.01
GSD_COMPUTATION_MAXIMUM_VALUE = 2.0

FORMAT_LANDXML = 'LandXml'
FORMAT_LANDXML_EXTENSION = 'xml'
extension_by_format = {}
extension_by_format[FORMAT_LANDXML] = FORMAT_LANDXML_EXTENSION

FIELD_ID = "Id"
FIELD_ENABLED = "Enabled"
FIELD_DESCRIPTION = "Description"
FIELD_CRS = "CRS"
FIELD_CONTENT = "Content"
FIELD_AXIS3D = "Axis 3D"
FIELD_PROFILE = "Profile"
FIELD_TRIANGULATION_PLY = "Triangulation PLY"
FIELD_ROI_WIDTH = "Roi Width"
FIELD_ROI = "Roi"
FIELD_GSD_VOLUMES_COMPUTATION = "GSD"
FIELD_SOURCE_FILE = "Source file"
FIELD_TRIANGULATION_POINTS = "Triangulation Points"
FIELD_TRIANGULATION_TRIANGLES = "Triangulation Triangles"
fields = [FIELD_ID, FIELD_ENABLED, FIELD_DESCRIPTION,
          FIELD_CRS, FIELD_CONTENT, FIELD_AXIS3D, FIELD_PROFILE,
          FIELD_TRIANGULATION_PLY, FIELD_ROI_WIDTH, FIELD_ROI, FIELD_GSD_VOLUMES_COMPUTATION, FIELD_SOURCE_FILE,
          FIELD_TRIANGULATION_TRIANGLES, FIELD_TRIANGULATION_POINTS]
# no in fields
FIELD_MINIMUM_X = "min_x"
FIELD_MAXIMUM_X = "max_x"
FIELD_MINIMUM_Y = "min_y"
FIELD_MAXIMUM_Y = "max_y"
FIELD_BB_WKT = "wkt_bb"

HEADER_ID_TAG = FIELD_ID
HEADER_ENABLED_TAG = FIELD_ENABLED
HEADER_DESCRIPTION_TAG = FIELD_DESCRIPTION
HEADER_CRS_TAG = FIELD_CRS
HEADER_CONTENT_TAG = FIELD_CONTENT
HEADER_AXIS3D_TAG = FIELD_AXIS3D
HEADER_PROFILE_TAG = FIELD_PROFILE
HEADER_TRIANGULATION_PLY_TAG = FIELD_TRIANGULATION_PLY
HEADER_ROI_WIDTH_TAG = FIELD_ROI_WIDTH
HEADER_ROI_TAG = FIELD_ROI
HEADER_GSD_VOLUMES_COMPUTATION_TAG = FIELD_GSD_VOLUMES_COMPUTATION
HEADER_SOURCE_FILE_TAG = FIELD_SOURCE_FILE
headers = [HEADER_ID_TAG,
           HEADER_ENABLED_TAG,
           HEADER_DESCRIPTION_TAG,
           HEADER_CRS_TAG,
           HEADER_CONTENT_TAG,
           HEADER_AXIS3D_TAG,
           HEADER_PROFILE_TAG,
           HEADER_TRIANGULATION_PLY_TAG,
           HEADER_ROI_WIDTH_TAG,
           HEADER_ROI_TAG,
           HEADER_GSD_VOLUMES_COMPUTATION_TAG,
           HEADER_SOURCE_FILE_TAG]
HEADER_ID_TOOLTIP = "Geometric design project identifier"
HEADER_ENABLE_TOOLTIP = "Enabled"
HEADER_DESCRIPTION_TOOLTIP = "Description"
HEADER_CRS_TOOLTIP = "CRS"
HEADER_CONTENT_TOOLTIP = "Content as JSON"
HEADER_AXIS3D_TOOLTIP = "Axis 3D as WKT"
HEADER_PROFILE_TOOLTIP = "Profile as WKT: cumulative distance and height"
HEADER_TRIANGULATION_PLY = "Triangulation as PLY"
HEADER_ROI_WIDTH = "Region Of Interest Width (m)"
HEADER_ROI = "Region Of Interest as WKT"
HEADER_GSD_VOLUMES_COMPUTATION = "GSD volumes computation (m)"
HEADER_SOURCE_FILE_TOOLTIP = "Source file"
header_tooltips = [HEADER_ID_TOOLTIP,
                   HEADER_ENABLE_TOOLTIP,
                   HEADER_DESCRIPTION_TOOLTIP,
                   HEADER_CRS_TOOLTIP,
                   HEADER_CONTENT_TOOLTIP,
                   HEADER_AXIS3D_TOOLTIP,
                   HEADER_PROFILE_TOOLTIP,
                   HEADER_TRIANGULATION_PLY,
                   HEADER_ROI_WIDTH,
                   HEADER_ROI,
                   HEADER_GSD_VOLUMES_COMPUTATION,
                   HEADER_SOURCE_FILE_TOOLTIP]

