# authors:
# David Hernandez Lopez, david.hernandez@uclm.es

from pyLibGDAL import defs_gdal

DIALOG_TITLE = "Volumes Computations"
# CONST_NO_COMBO_SELECT = " ... "
# CONST_NO_COMBO_SELECT = " ... "
RESUME_CONTENT = "Click to view"
VOLUME_TYPE_DTMS_DIFFERENCE = "DTMSs Difference"
VOLUME_TYPE_DSMS_DIFFERENCE = "DSMs Difference"
VOLUME_TYPE_GD_DTM_DIFFERENCE = "Geo.Design - DTM"
VOLUME_TYPE_GD_DSM_DIFFERENCE = "Geo.Desing - DSM"

FIELD_ID = "Id"
FIELD_GDP_ID = "GDP Id"
FIELD_ENABLED = "Enabled"
FIELD_VOLUME_DATE_FROM = "Date From"
FIELD_VOLUME_DATE_TO = "Date To"
FIELD_VOLUME_TYPE = "Type"
FIELD_CRS = "CRS"
FIELD_RASTER_FILE_RESULT = "Raster Result"
FIELD_RASTER_FILE_FROM = "Raster From"
FIELD_RASTER_FILE_TO = "Raster To"
FIELD_DESCRIPTION = "Description"
# FIELD_CONTENT = "Content"
fields = [FIELD_ID,
          FIELD_GDP_ID,
          FIELD_ENABLED,
          FIELD_VOLUME_DATE_FROM,
          FIELD_VOLUME_DATE_TO,
          FIELD_VOLUME_TYPE,
          FIELD_CRS,
          FIELD_RASTER_FILE_RESULT,
          FIELD_RASTER_FILE_FROM,
          FIELD_RASTER_FILE_TO,
          FIELD_DESCRIPTION]
          # FIELD_DESCRIPTION,
          # FIELD_CONTENT]
FIELD_RASTER_FILE_RESULT_GEOJSON = "Raster Result GeoJSON"
FIELD_RASTER_FILE_FROM_GEOJSON = "Raster From GeoJSON"
FIELD_RASTER_FILE_TO_GEOJSON = "Raster To GeoJSON"

HEADER_ID_TAG = FIELD_ID
HEADER_GDP_ID_TAG = FIELD_GDP_ID
HEADER_ENABLED_TAG = FIELD_ENABLED
HEADER_VOLUME_DATE_FROM_TAG = FIELD_VOLUME_DATE_FROM
HEADER_VOLUME_DATE_TO_TAG = FIELD_VOLUME_DATE_TO
HEADER_VOLUME_TYPE_TAG = FIELD_VOLUME_TYPE
HEADER_CRS_TAG = FIELD_CRS
HEADER_RASTER_FILE_RESULT_TAG = FIELD_RASTER_FILE_RESULT
HEADER_RASTER_FILE_FROM_TAG = FIELD_RASTER_FILE_FROM
HEADER_RASTER_FILE_TO_TAG = FIELD_RASTER_FILE_TO
HEADER_DESCRIPTION_TAG = FIELD_DESCRIPTION
# HEADER_CONTENT_TAG = FIELD_CONTENT
headers = [HEADER_ID_TAG,
           HEADER_GDP_ID_TAG,
           HEADER_ENABLED_TAG,
           HEADER_VOLUME_DATE_FROM_TAG,
           HEADER_VOLUME_DATE_TO_TAG,
           HEADER_VOLUME_TYPE_TAG,
           HEADER_CRS_TAG,
           HEADER_RASTER_FILE_RESULT_TAG,
           HEADER_RASTER_FILE_FROM_TAG,
           HEADER_RASTER_FILE_TO_TAG,
           HEADER_DESCRIPTION_TAG]
           # HEADER_DESCRIPTION_TAG,
           # HEADER_CONTENT_TAG]

HEADER_ID_TOOLTIP = "Id"
HEADER_GPD_ID_TOOLTIP = "Geometric Design Project Id"
HEADER_ENABLED_TOOLTIP = "Enabled"
HEADER_VOLUME_DATE_FROM_TOOLTIP = "Date From"
HEADER_VOLUME_DATE_TO_TOOLTIP = "Date To"
HEADER_VOLUME_TYPE_TOOLTIP = "Volume Type"
HEADER_CRS_TOOLTIP = "CRS"
HEADER_RASTER_FILE_RESULT_TOOLTIP = "Raster File Result"
HEADER_RASTER_FILE_FROM_TOOLTIP = "Raster File From"
HEADER_RASTER_FILE_TO_TOOLTIP = "Raster File To"
HEADER_DESCRIPTION_TOOLTIP = "Description"
# HEADER_CONTENT_TOOLTIP = "Content"
header_tooltips = [HEADER_ID_TAG,
                   HEADER_GPD_ID_TOOLTIP,
                   HEADER_ENABLED_TOOLTIP,
                   HEADER_VOLUME_DATE_FROM_TOOLTIP,
                   HEADER_VOLUME_DATE_TO_TOOLTIP,
                   HEADER_VOLUME_TYPE_TOOLTIP,
                   HEADER_CRS_TOOLTIP,
                   HEADER_RASTER_FILE_RESULT_TOOLTIP,
                   HEADER_RASTER_FILE_FROM_TOOLTIP,
                   HEADER_RASTER_FILE_TO_TOOLTIP,
                   HEADER_DESCRIPTION_TOOLTIP]
                   # HEADER_DESCRIPTION_TOOLTIP,
                   # HEADER_CONTENT_TOOLTIP]

VOLUME_RASTER_FILE_SUFIX = "vol"

GEOJSON_FP_LAYER_NAME = "contour"
GEOJSON_FP_FIELD_FEATURES = "features"
GEOJSON_FP_FIELD_FEATURES_GEOMETRY = "geometry"
geojson_fp_fields = {}
geojson_fp_fields[GEOJSON_FP_FIELD_FEATURES_GEOMETRY] = defs_gdal.geometry_type_by_name['polygon']

# JSON_FP_FIELD_FEATURES_GEOMETRY_NULL = null


